### ISSUE TITLE
Got a strange error

### ISSUE THREAD

**Issue by rygel** [isaacs/node-touch#4]
When I was trying to use this module I got the following error:

``` javascript
ReferenceError: document is not defined
 at module.exports (C:\Develop\trunk\node_modules\node-touch\node_modules\node-inserted\index.js:5:12)
 at Object.<anonymous> (C:\Develop\trunk\node_modules\node-touch\index.js:1:87)
```

I am using node 0.10.32 on Windows 7 64bit.

**Comment by cadesalaberry** [comment]
Ran into the same problem, thanks @rygel.

**Comment by cadesalaberry** [comment]
I would suggest to put `ReferenceError: document is not defined` in the title of the issue for future references.
