### ISSUE TITLE
fd = 18 when passed in path

### ISSUE THREAD

**Issue by knownasilya** [isaacs/node-touch#5]
Passed in a path, e.g. `/var/www/myapp/.restart`, to `touch.sync(path)`, but touch tries to do `fs.futimesSync` with `fd` having the value `18`. All of this happens here: https://github.com/isaacs/node-touch/blob/master/touch.js#L127 and I get an EPERM error, since 18 doesn't exist.

**Comment by knownasilya** [comment]
Although here is a stacktrace:

```no-highlight
fs.js:1096
  binding.futimes(fd, atime, mtime);
          ^

Error: EPERM: operation not permitted, futime
    at Error (native)
    at Object.fs.futimesSync (fs.js:1096:11)
    at thenFutimes (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:127:46)
    at fstatThenFutimes (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:98:46)
    at ftouch_ (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:94:10)
    at optionsRef (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:41:28)
    at ftouch (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:89:10)
    at /var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:84:10
    at openThenF (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:76:30)
    at touch_ (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:69:10)
    at optionsRef (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:41:28)
    at touch (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:65:10)
    at Function.touch.touchSync.touch.sync (/var/www/strider/node_modules/strider-cli/node_modules/touch/touch.js:6:10)
    at restart (/var/www/strider/node_modules/strider-cli/resilient.js:9:13)
    at /var/www/strider/lib/routes/admin/plugins/index.js:31:7
    at /var/www/strider/node_modules/strider-cli/plugin_manager/install_plugin.js:45:17
    at ChildProcess.<anonymous> (/var/www/strider/node_modules/strider-cli/plugin_manager/npm.js:19:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
